feature: enable gesture to change emoji category with horizontal swipe gesture
TheWidlarzGroup/rn-emoji-keyboard pull request #100
Opened 2022-11-09 10:49 UTC by pierre275

# Description
This pr adds new props `enableCategoryChangeGesture` which let user to change category with horizontal swipe

#### How to test
Follow provided documentation and check added usage example

2022-11-25 22:10 UTC, jakex7 requested changes
Great feature, but it needs a little tuning to be included. For a better user experience, the category Indicator should be moved during scroll as well.
If you need more details please let me know 😃 

![image](https://user-images.githubusercontent.com/39670088/204059278-393bebbe-0c83-45fe-b3ab-2e25438180b2.png)

2022-12-03 09:31 UTC, oferRounds reviewed
Great-needed feature

2022-12-03 09:31 UTC, oferRounds commented on src/contexts/KeyboardContext.tsx
> +  enableCategoryChangeGesture?: boolean
missing also from `defaultKeyboardValues` object

2022-12-03 09:32 UTC, oferRounds commented on src/contexts/KeyboardContext.tsx
> +  enableCategoryChangeGesture?: boolean
I see now that `enableCategoryChangeGesture` is also missing from there

2022-12-20 14:17 UTC, mateki0 commented
> Great feature, but it needs a little tuning to be included. For a better user experience, the category Indicator should be moved during scroll as well. If you need more details please let me know 😃
> 
> ![image](https://user-images.githubusercontent.com/39670088/204059278-393bebbe-0c83-45fe-b3ab-2e25438180b2.png)

I've added this feature in the latest commit

2022-12-22 22:07 UTC, jakex7 commented on src/components/EmojiStaticKeyboard.tsx
> +        scrollNav.setValue(index * CATEGORY_ELEMENT_WIDTH)
I've just changed Spring animation to setValue because now animation feel lot more responsive @mateki0

2022-12-22 22:12 UTC, jakex7 commented
Thanks @pierre275 @mateki0, It's so great that i've enabled it by default 🚀

2022-12-22 22:12 UTC, jakex7 approved these changes

2022-12-22 22:12 UTC, merged