Feature / recently used emojis
TheWidlarzGroup/rn-emoji-keyboard pull request #14
Opened 2021-07-28 12:45 UTC by jakex7

**What changed:**
* Added `enableRecentlyUsed` boolean prop with default false value
* Added example
* README improvement

**Preview:**
![enable-recently-used-preview](https://user-images.githubusercontent.com/39670088/127324256-d0860673-dbc0-4ea0-9e63-5a05e2a721de.jpg)

2021-07-29 10:51 UTC, KacperM717 approved these changes
Cool changes :) In future, we could consider using recentlyUsed as regular category and conditionally adding it to disabledCategories in context. That way, all these "ifs" in components (Keyboard and Category) could go away.

2021-07-29 11:28 UTC, spaceowlpurrp requested changes

2021-07-29 11:28 UTC, spaceowlpurrp commented on src/components/EmojiStaticKeyboard.tsx
> +    if (keyboardState.recentlyUsed.length)
add curly braces to improve readability of this statement

2021-07-29 11:28 UTC, spaceowlpurrp commented on src/components/EmojiStaticKeyboard.tsx
> +  const renderList = React.useCallback(() => {
replace this useCallback with useMemo:
-this function is called on every rerender, so it must calculate new array
-this function always returns different array(reference)

2021-07-30 10:49 UTC, spaceowlpurrp approved these changes

2021-07-30 10:53 UTC, merged